import { Client, Project, Task, Campaign, Content, User, Notification } from '@/types';

export const users: User[] = [
  { 
    id: '1', 
    name: 'Admin User', 
    email: 'admin@crm.com', 
    role: 'admin',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    phone: '+20 100 123 4567',
    department: 'Management',
    joinedAt: '2024-01-01',
    approvedBy: 'System',
    approvedAt: '2024-01-01'
  },
  { 
    id: '2', 
    name: 'Ahmed Hassan', 
    email: 'ahmed@crm.com', 
    role: 'graphic-designer',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
    phone: '+20 101 234 5678',
    department: 'Design',
    joinedAt: '2024-06-15',
    approvedBy: 'Admin User',
    approvedAt: '2024-06-16'
  },
  { 
    id: '3', 
    name: 'Sara Mohamed', 
    email: 'sara@crm.com', 
    role: 'social-media',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
    phone: '+20 102 345 6789',
    department: 'Marketing',
    joinedAt: '2024-08-20',
    approvedBy: 'Admin User',
    approvedAt: '2024-08-21'
  },
  { 
    id: '4', 
    name: 'Omar Ali', 
    email: 'omar@crm.com', 
    role: 'content-writer',
    status: 'pending',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Omar',
    phone: '+20 103 456 7890',
    department: 'Content',
    joinedAt: '2025-09-28'
  },
  { 
    id: '5', 
    name: 'Mona Ibrahim', 
    email: 'mona@crm.com', 
    role: 'video-editor',
    status: 'pending',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mona',
    phone: '+20 104 567 8901',
    department: 'Production',
    joinedAt: '2025-09-29'
  },
  { 
    id: '6', 
    name: 'Youssef Khaled', 
    email: 'youssef@crm.com', 
    role: 'ads-specialist',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Youssef',
    phone: '+20 105 678 9012',
    department: 'Advertising',
    joinedAt: '2024-07-10',
    approvedBy: 'Admin User',
    approvedAt: '2024-07-11'
  },
  { 
    id: '7', 
    name: 'Heba Samir', 
    email: 'heba@crm.com', 
    role: 'seo-specialist',
    status: 'suspended',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Heba',
    phone: '+20 106 789 0123',
    department: 'SEO',
    joinedAt: '2024-05-05',
    approvedBy: 'Admin User',
    approvedAt: '2024-05-06'
  },
  { 
    id: '8', 
    name: 'Karim Mostafa', 
    email: 'karim@crm.com', 
    role: 'account-manager',
    status: 'active',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karim',
    phone: '+20 107 890 1234',
    department: 'Client Services',
    joinedAt: '2024-03-15',
    approvedBy: 'Admin User',
    approvedAt: '2024-03-16'
  },
];

export const clients: Client[] = [
  {
    id: '1',
    name: 'TechStart Inc.',
    contactPerson: 'David Wilson',
    phone: '+1 234 567 8900',
    email: 'david@techstart.com',
    company: 'TechStart Inc.',
    notes: 'Looking for comprehensive digital marketing solutions.',
    linkedProjects: ['1', '2'],
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    name: 'GreenLife Solutions',
    contactPerson: 'Lisa Green',
    phone: '+1 234 567 8901',
    email: 'lisa@greenlife.com',
    company: 'GreenLife Solutions',
    notes: 'Eco-friendly products, focus on sustainability messaging.',
    linkedProjects: ['3'],
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    name: 'FitZone Gym',
    contactPerson: 'Mark Strong',
    phone: '+1 234 567 8902',
    email: 'mark@fitzone.com',
    company: 'FitZone Gym',
    notes: 'New gym chain, needs social media presence.',
    linkedProjects: ['4'],
    createdAt: '2025-03-10',
  },
];

export const projects: Project[] = [
  {
    id: '1',
    name: 'TechStart Q1 Campaign',
    description: 'Comprehensive digital marketing campaign for Q1 product launch.',
    clientId: '1',
    startDate: '2025-01-20',
    endDate: '2025-03-31',
    status: 'in-progress',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['1', '2', '3'],
    linkedCampaigns: ['1', '2'],
    linkedContent: ['1', '2', '3'],
    progress: 65,
    files: [],
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    name: 'TechStart Website Redesign',
    description: 'Complete website overhaul with modern design and SEO optimization.',
    clientId: '1',
    startDate: '2025-02-01',
    endDate: '2025-04-30',
    status: 'in-progress',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['4', '5'],
    linkedCampaigns: [],
    linkedContent: ['4'],
    progress: 40,
    files: [],
    createdAt: '2025-01-20',
  },
  {
    id: '3',
    name: 'GreenLife Social Media Strategy',
    description: 'Monthly social media content and engagement strategy.',
    clientId: '2',
    startDate: '2025-02-15',
    endDate: '2025-08-15',
    status: 'in-progress',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['6', '7'],
    linkedCampaigns: ['3'],
    linkedContent: ['5', '6', '7'],
    progress: 55,
    files: [],
    createdAt: '2025-02-01',
  },
  {
    id: '4',
    name: 'FitZone Grand Opening',
    description: 'Marketing campaign for grand opening event.',
    clientId: '3',
    startDate: '2025-03-15',
    endDate: '2025-05-01',
    status: 'planned',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['8'],
    linkedCampaigns: ['4'],
    linkedContent: ['8'],
    progress: 15,
    files: [],
    createdAt: '2025-03-10',
  },
];

export const tasks: Task[] = [
  {
    id: '1',
    title: 'Create Facebook Ad Creatives',
    description: 'Design 5 different ad creatives for the Q1 campaign.',
    type: 'graphic-design',
    status: 'in-progress',
    priority: 'high',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-01-25',
    dueDate: '2025-02-05',
    attachments: [],
    comments: [],
    progress: 60,
    subtasks: [
      { id: '1-1', title: 'Product showcase ad', completed: true },
      { id: '1-2', title: 'Testimonial ad', completed: true },
      { id: '1-3', title: 'Feature highlight ad', completed: false },
      { id: '1-4', title: 'Limited offer ad', completed: false },
      { id: '1-5', title: 'Brand awareness ad', completed: false },
    ],
    projectId: '1',
    createdAt: '2025-01-22',
    changeLog: [],
  },
  {
    id: '2',
    title: 'Write Blog Post - Product Features',
    description: 'Write a comprehensive blog post about new product features.',
    type: 'content-writing',
    status: 'review',
    priority: 'medium',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-01-20',
    dueDate: '2025-02-01',
    completionDate: '2025-01-30',
    attachments: [],
    comments: [
      { id: '1', text: 'First draft completed, ready for review', author: 'Emily Davis', createdAt: '2025-01-30' },
    ],
    progress: 90,
    subtasks: [],
    projectId: '1',
    createdAt: '2025-01-18',
    changeLog: [],
  },
  {
    id: '3',
    title: 'Setup Google Ads Campaign',
    description: 'Configure and launch Google Ads campaign for product launch.',
    type: 'ads-setup',
    status: 'to-do',
    priority: 'urgent',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-10',
    dueDate: '2025-02-15',
    attachments: [],
    comments: [],
    progress: 0,
    subtasks: [],
    projectId: '1',
    createdAt: '2025-01-25',
    changeLog: [],
  },
  {
    id: '4',
    title: 'Website SEO Audit',
    description: 'Complete SEO audit of current website before redesign.',
    type: 'seo',
    status: 'done',
    priority: 'high',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-01',
    dueDate: '2025-02-10',
    completionDate: '2025-02-08',
    attachments: [],
    comments: [],
    progress: 100,
    subtasks: [],
    projectId: '2',
    createdAt: '2025-01-28',
    changeLog: [],
  },
  {
    id: '5',
    title: 'Create Homepage Design Mockups',
    description: 'Design 3 different homepage mockups for client review.',
    type: 'graphic-design',
    status: 'in-progress',
    priority: 'high',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-12',
    dueDate: '2025-02-25',
    attachments: [],
    comments: [],
    progress: 45,
    subtasks: [],
    projectId: '2',
    createdAt: '2025-02-10',
    changeLog: [],
  },
  {
    id: '6',
    title: 'Create Instagram Content Calendar',
    description: 'Plan Instagram posts for the next month.',
    type: 'content-writing',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-20',
    dueDate: '2025-03-01',
    attachments: [],
    comments: [],
    progress: 70,
    subtasks: [],
    projectId: '3',
    createdAt: '2025-02-18',
    changeLog: [],
  },
  {
    id: '7',
    title: 'Create Eco-Friendly Product Video',
    description: 'Produce a 60-second video highlighting eco-friendly products.',
    type: 'video-editing',
    status: 'delayed',
    priority: 'high',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-15',
    dueDate: '2025-02-28',
    attachments: [],
    comments: [],
    progress: 30,
    subtasks: [],
    projectId: '3',
    createdAt: '2025-02-12',
    changeLog: [],
  },
  {
    id: '8',
    title: 'Design Grand Opening Flyers',
    description: 'Create print and digital flyers for grand opening event.',
    type: 'graphic-design',
    status: 'to-do',
    priority: 'medium',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-20',
    dueDate: '2025-04-01',
    attachments: [],
    comments: [],
    progress: 0,
    subtasks: [],
    projectId: '4',
    createdAt: '2025-03-15',
    changeLog: [],
  },
];

export const campaigns: Campaign[] = [
  {
    id: '1',
    name: 'TechStart Facebook Launch Campaign',
    projectId: '1',
    type: 'facebook-ads',
    objective: 'sales',
    startDate: '2025-02-01',
    endDate: '2025-03-31',
    budget: 15000,
    status: 'running',
    responsiblePerson: '3',
    kpis: [
      { name: 'CTR', value: '3.2%' },
      { name: 'CPC', value: '$0.85' },
      { name: 'Conversions', value: '234' },
      { name: 'ROAS', value: '4.2x' },
    ],
    attachments: [],
    createdBy: '2',
    progress: 55,
    createdAt: '2025-01-28',
  },
  {
    id: '2',
    name: 'Google Ads - Product Launch',
    projectId: '1',
    type: 'google-ads',
    objective: 'leads',
    startDate: '2025-02-15',
    endDate: '2025-03-31',
    budget: 20000,
    status: 'planned',
    responsiblePerson: '3',
    kpis: [],
    attachments: [],
    createdBy: '2',
    progress: 20,
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    name: 'GreenLife Instagram Awareness',
    projectId: '3',
    type: 'instagram-ads',
    objective: 'awareness',
    startDate: '2025-03-01',
    endDate: '2025-05-31',
    budget: 8000,
    status: 'running',
    responsiblePerson: '3',
    kpis: [
      { name: 'Reach', value: '125K' },
      { name: 'Engagement Rate', value: '5.8%' },
      { name: 'CPM', value: '$4.20' },
    ],
    attachments: [],
    createdBy: '2',
    progress: 40,
    createdAt: '2025-02-25',
  },
  {
    id: '4',
    name: 'FitZone Grand Opening Campaign',
    projectId: '4',
    type: 'facebook-ads',
    objective: 'engagement',
    startDate: '2025-04-01',
    endDate: '2025-05-01',
    budget: 5000,
    status: 'planned',
    responsiblePerson: '3',
    kpis: [],
    attachments: [],
    createdBy: '2',
    progress: 10,
    createdAt: '2025-03-12',
  },
];

export const content: Content[] = [
  {
    id: '1',
    title: 'Product Launch Announcement Post',
    contentType: 'post',
    projectId: '1',
    campaignId: '1',
    status: 'published',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-01-25',
    dueDate: '2025-02-01',
    publishDate: '2025-02-01',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-01-22',
    month: '2025-02',
    isReel: false,
    designBrief: 'Create an engaging product launch announcement',
    inspiration: 'Tech startup launches',
    design: 'Modern gradient design with product images',
    textContent: 'Introducing our revolutionary product!',
    driveLink: 'https://drive.google.com/file/xxx',
    notes: 'Published successfully',
    readyForCalendar: false,
  },
  {
    id: '2',
    title: 'Feature Highlight Video',
    contentType: 'video',
    projectId: '1',
    campaignId: '1',
    status: 'review',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-01',
    dueDate: '2025-02-15',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 80,
    createdAt: '2025-01-28',
  },
  {
    id: '3',
    title: 'Customer Testimonial Graphics',
    contentType: 'graphic',
    projectId: '1',
    status: 'in-progress',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-10',
    dueDate: '2025-02-20',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 60,
    createdAt: '2025-02-08',
  },
  {
    id: '4',
    title: 'Website Redesign Blog Article',
    contentType: 'article',
    projectId: '2',
    status: 'idea',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-01',
    dueDate: '2025-03-15',
    priority: 'low',
    attachments: [],
    comments: [],
    progress: 0,
    createdAt: '2025-02-25',
  },
  {
    id: '5',
    title: 'Eco Tips Instagram Post Series',
    contentType: 'post',
    projectId: '3',
    campaignId: '3',
    status: 'scheduled',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-20',
    dueDate: '2025-03-01',
    publishDate: '2025-03-05',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-02-18',
  },
  {
    id: '6',
    title: 'Product Showcase Video',
    contentType: 'video',
    projectId: '3',
    status: 'in-progress',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-25',
    dueDate: '2025-03-10',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 45,
    createdAt: '2025-02-22',
  },
  {
    id: '7',
    title: 'Sustainability Email Newsletter',
    contentType: 'email',
    projectId: '3',
    status: 'approved',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-01',
    dueDate: '2025-03-08',
    publishDate: '2025-03-10',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-02-28',
  },
  {
    id: '8',
    title: 'Grand Opening Event Graphics',
    contentType: 'graphic',
    projectId: '4',
    campaignId: '4',
    status: 'idea',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-20',
    dueDate: '2025-04-01',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 0,
    createdAt: '2025-03-15',
    month: '2025-04',
    isReel: false,
    readyForCalendar: false,
  },
  // Ready Content for Calendar
  {
    id: '9',
    title: 'Spring Sale Announcement',
    contentType: 'post',
    projectId: '1',
    status: 'approved',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-10-01',
    dueDate: '2025-10-05',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-09-28',
    month: '2025-10',
    isReel: false,
    designBrief: 'Create eye-catching spring sale announcement',
    inspiration: 'Seasonal marketing campaigns',
    design: 'Spring colors with discount badge',
    textContent: '🌸 Spring Sale! Up to 40% OFF on all products!',
    driveLink: 'https://drive.google.com/file/spring-sale',
    notes: 'Ready for social media',
    readyForCalendar: true,
  },
  {
    id: '10',
    title: 'Customer Success Story',
    contentType: 'post',
    projectId: '1',
    status: 'approved',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-10-01',
    dueDate: '2025-10-10',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-09-29',
    month: '2025-10',
    isReel: false,
    designBrief: 'Showcase customer testimonial',
    inspiration: 'Social proof content',
    design: 'Quote card with customer photo',
    textContent: '"This product changed my business!" - Sarah J.',
    driveLink: 'https://drive.google.com/file/testimonial',
    notes: 'Approved by client',
    readyForCalendar: true,
  },
  {
    id: '11',
    title: 'Product Demo Reel',
    contentType: 'video',
    projectId: '1',
    status: 'approved',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-10-01',
    dueDate: '2025-10-08',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-09-27',
    month: '2025-10',
    isReel: true,
    designBrief: 'Quick 30-second product demo',
    inspiration: 'Product showcase reels',
    design: 'Dynamic transitions with product features',
    textContent: 'See how easy it is to use our product! ✨',
    driveLink: 'https://drive.google.com/file/demo-reel',
    notes: 'Final version approved',
    readyForCalendar: true,
  },
  {
    id: '12',
    title: 'Behind the Scenes Reel',
    contentType: 'video',
    projectId: '1',
    status: 'approved',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-10-02',
    dueDate: '2025-10-12',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-09-30',
    month: '2025-10',
    isReel: true,
    designBrief: 'Show team working on projects',
    inspiration: 'BTS content',
    design: 'Candid shots with upbeat music',
    textContent: 'A day in our creative studio 🎨',
    driveLink: 'https://drive.google.com/file/bts-reel',
    notes: 'Great engagement expected',
    readyForCalendar: true,
  },
  {
    id: '13',
    title: 'Eco Tips Carousel',
    contentType: 'post',
    projectId: '3',
    status: 'approved',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-10-01',
    dueDate: '2025-10-06',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-09-28',
    month: '2025-10',
    isReel: false,
    designBrief: '5 eco tips for sustainable living',
    inspiration: 'Educational carousel posts',
    design: 'Green theme with icons',
    textContent: '🌱 5 Easy Ways to Live More Sustainably',
    driveLink: 'https://drive.google.com/file/eco-tips',
    notes: 'Part of sustainability campaign',
    readyForCalendar: true,
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    type: 'deadline',
    title: 'Task Due Soon',
    message: 'Setup Google Ads Campaign is due in 2 days',
    link: '/tasks/3',
    read: false,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: '2',
    type: 'comment',
    title: 'New Comment',
    message: 'Emily Davis commented on "Write Blog Post - Product Features"',
    link: '/tasks/2',
    read: false,
    createdAt: '2025-09-30T14:30:00Z',
  },
  {
    id: '3',
    type: 'status-update',
    title: 'Task Completed',
    message: 'Website SEO Audit has been marked as complete',
    link: '/tasks/4',
    read: true,
    createdAt: '2025-09-29T10:15:00Z',
  },
  {
    id: '4',
    type: 'assignment',
    title: 'New Task Assigned',
    message: 'You have been assigned to "Design Grand Opening Flyers"',
    link: '/tasks/8',
    read: true,
    createdAt: '2025-09-28T09:00:00Z',
  },
];

