import { Client, Project, Task, Campaign, Content, User, Notification } from '@/types';

export const users: User[] = [
  { id: '1', name: 'John Doe', email: 'john@agency.com', role: 'admin', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John' },
  { id: '2', name: 'Sarah Smith', email: 'sarah@agency.com', role: 'project-manager', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah' },
  { id: '3', name: 'Mike Johnson', email: 'mike@agency.com', role: 'team-member', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike' },
  { id: '4', name: 'Emily Davis', email: 'emily@agency.com', role: 'team-member', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily' },
  { id: '5', name: 'David Wilson', email: 'david@client.com', role: 'client', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David' },
];

export const clients: Client[] = [
  {
    id: '1',
    name: 'TechStart Inc.',
    contactPerson: 'David Wilson',
    phone: '+1 234 567 8900',
    email: 'david@techstart.com',
    company: 'TechStart Inc.',
    notes: 'Looking for comprehensive digital marketing solutions.',
    linkedProjects: ['1', '2'],
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    name: 'GreenLife Solutions',
    contactPerson: 'Lisa Green',
    phone: '+1 234 567 8901',
    email: 'lisa@greenlife.com',
    company: 'GreenLife Solutions',
    notes: 'Eco-friendly products, focus on sustainability messaging.',
    linkedProjects: ['3'],
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    name: 'FitZone Gym',
    contactPerson: 'Mark Strong',
    phone: '+1 234 567 8902',
    email: 'mark@fitzone.com',
    company: 'FitZone Gym',
    notes: 'New gym chain, needs social media presence.',
    linkedProjects: ['4'],
    createdAt: '2025-03-10',
  },
];

export const projects: Project[] = [
  {
    id: '1',
    name: 'TechStart Q1 Campaign',
    description: 'Comprehensive digital marketing campaign for Q1 product launch.',
    clientId: '1',
    startDate: '2025-01-20',
    endDate: '2025-03-31',
    status: 'in-progress',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['1', '2', '3'],
    linkedCampaigns: ['1', '2'],
    linkedContent: ['1', '2', '3'],
    progress: 65,
    files: [],
    createdAt: '2025-01-15',
  },
  {
    id: '2',
    name: 'TechStart Website Redesign',
    description: 'Complete website overhaul with modern design and SEO optimization.',
    clientId: '1',
    startDate: '2025-02-01',
    endDate: '2025-04-30',
    status: 'in-progress',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['4', '5'],
    linkedCampaigns: [],
    linkedContent: ['4'],
    progress: 40,
    files: [],
    createdAt: '2025-01-20',
  },
  {
    id: '3',
    name: 'GreenLife Social Media Strategy',
    description: 'Monthly social media content and engagement strategy.',
    clientId: '2',
    startDate: '2025-02-15',
    endDate: '2025-08-15',
    status: 'in-progress',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['6', '7'],
    linkedCampaigns: ['3'],
    linkedContent: ['5', '6', '7'],
    progress: 55,
    files: [],
    createdAt: '2025-02-01',
  },
  {
    id: '4',
    name: 'FitZone Grand Opening',
    description: 'Marketing campaign for grand opening event.',
    clientId: '3',
    startDate: '2025-03-15',
    endDate: '2025-05-01',
    status: 'planned',
    projectManager: '2',
    createdBy: '1',
    linkedTasks: ['8'],
    linkedCampaigns: ['4'],
    linkedContent: ['8'],
    progress: 15,
    files: [],
    createdAt: '2025-03-10',
  },
];

export const tasks: Task[] = [
  {
    id: '1',
    title: 'Create Facebook Ad Creatives',
    description: 'Design 5 different ad creatives for the Q1 campaign.',
    type: 'graphic-design',
    status: 'in-progress',
    priority: 'high',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-01-25',
    dueDate: '2025-02-05',
    attachments: [],
    comments: [],
    progress: 60,
    subtasks: [
      { id: '1-1', title: 'Product showcase ad', completed: true },
      { id: '1-2', title: 'Testimonial ad', completed: true },
      { id: '1-3', title: 'Feature highlight ad', completed: false },
      { id: '1-4', title: 'Limited offer ad', completed: false },
      { id: '1-5', title: 'Brand awareness ad', completed: false },
    ],
    projectId: '1',
    createdAt: '2025-01-22',
    changeLog: [],
  },
  {
    id: '2',
    title: 'Write Blog Post - Product Features',
    description: 'Write a comprehensive blog post about new product features.',
    type: 'content-writing',
    status: 'review',
    priority: 'medium',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-01-20',
    dueDate: '2025-02-01',
    completionDate: '2025-01-30',
    attachments: [],
    comments: [
      { id: '1', text: 'First draft completed, ready for review', author: 'Emily Davis', createdAt: '2025-01-30' },
    ],
    progress: 90,
    subtasks: [],
    projectId: '1',
    createdAt: '2025-01-18',
    changeLog: [],
  },
  {
    id: '3',
    title: 'Setup Google Ads Campaign',
    description: 'Configure and launch Google Ads campaign for product launch.',
    type: 'ads-setup',
    status: 'to-do',
    priority: 'urgent',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-10',
    dueDate: '2025-02-15',
    attachments: [],
    comments: [],
    progress: 0,
    subtasks: [],
    projectId: '1',
    createdAt: '2025-01-25',
    changeLog: [],
  },
  {
    id: '4',
    title: 'Website SEO Audit',
    description: 'Complete SEO audit of current website before redesign.',
    type: 'seo',
    status: 'done',
    priority: 'high',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-01',
    dueDate: '2025-02-10',
    completionDate: '2025-02-08',
    attachments: [],
    comments: [],
    progress: 100,
    subtasks: [],
    projectId: '2',
    createdAt: '2025-01-28',
    changeLog: [],
  },
  {
    id: '5',
    title: 'Create Homepage Design Mockups',
    description: 'Design 3 different homepage mockups for client review.',
    type: 'graphic-design',
    status: 'in-progress',
    priority: 'high',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-12',
    dueDate: '2025-02-25',
    attachments: [],
    comments: [],
    progress: 45,
    subtasks: [],
    projectId: '2',
    createdAt: '2025-02-10',
    changeLog: [],
  },
  {
    id: '6',
    title: 'Create Instagram Content Calendar',
    description: 'Plan Instagram posts for the next month.',
    type: 'content-writing',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-20',
    dueDate: '2025-03-01',
    attachments: [],
    comments: [],
    progress: 70,
    subtasks: [],
    projectId: '3',
    createdAt: '2025-02-18',
    changeLog: [],
  },
  {
    id: '7',
    title: 'Create Eco-Friendly Product Video',
    description: 'Produce a 60-second video highlighting eco-friendly products.',
    type: 'video-editing',
    status: 'delayed',
    priority: 'high',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-15',
    dueDate: '2025-02-28',
    attachments: [],
    comments: [],
    progress: 30,
    subtasks: [],
    projectId: '3',
    createdAt: '2025-02-12',
    changeLog: [],
  },
  {
    id: '8',
    title: 'Design Grand Opening Flyers',
    description: 'Create print and digital flyers for grand opening event.',
    type: 'graphic-design',
    status: 'to-do',
    priority: 'medium',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-20',
    dueDate: '2025-04-01',
    attachments: [],
    comments: [],
    progress: 0,
    subtasks: [],
    projectId: '4',
    createdAt: '2025-03-15',
    changeLog: [],
  },
];

export const campaigns: Campaign[] = [
  {
    id: '1',
    name: 'TechStart Facebook Launch Campaign',
    projectId: '1',
    type: 'facebook-ads',
    objective: 'sales',
    startDate: '2025-02-01',
    endDate: '2025-03-31',
    budget: 15000,
    status: 'running',
    responsiblePerson: '3',
    kpis: [
      { name: 'CTR', value: '3.2%' },
      { name: 'CPC', value: '$0.85' },
      { name: 'Conversions', value: '234' },
      { name: 'ROAS', value: '4.2x' },
    ],
    attachments: [],
    createdBy: '2',
    progress: 55,
    createdAt: '2025-01-28',
  },
  {
    id: '2',
    name: 'Google Ads - Product Launch',
    projectId: '1',
    type: 'google-ads',
    objective: 'leads',
    startDate: '2025-02-15',
    endDate: '2025-03-31',
    budget: 20000,
    status: 'planned',
    responsiblePerson: '3',
    kpis: [],
    attachments: [],
    createdBy: '2',
    progress: 20,
    createdAt: '2025-02-01',
  },
  {
    id: '3',
    name: 'GreenLife Instagram Awareness',
    projectId: '3',
    type: 'instagram-ads',
    objective: 'awareness',
    startDate: '2025-03-01',
    endDate: '2025-05-31',
    budget: 8000,
    status: 'running',
    responsiblePerson: '3',
    kpis: [
      { name: 'Reach', value: '125K' },
      { name: 'Engagement Rate', value: '5.8%' },
      { name: 'CPM', value: '$4.20' },
    ],
    attachments: [],
    createdBy: '2',
    progress: 40,
    createdAt: '2025-02-25',
  },
  {
    id: '4',
    name: 'FitZone Grand Opening Campaign',
    projectId: '4',
    type: 'facebook-ads',
    objective: 'engagement',
    startDate: '2025-04-01',
    endDate: '2025-05-01',
    budget: 5000,
    status: 'planned',
    responsiblePerson: '3',
    kpis: [],
    attachments: [],
    createdBy: '2',
    progress: 10,
    createdAt: '2025-03-12',
  },
];

export const content: Content[] = [
  {
    id: '1',
    title: 'Product Launch Announcement Post',
    contentType: 'post',
    projectId: '1',
    campaignId: '1',
    status: 'published',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-01-25',
    dueDate: '2025-02-01',
    publishDate: '2025-02-01',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-01-22',
  },
  {
    id: '2',
    title: 'Feature Highlight Video',
    contentType: 'video',
    projectId: '1',
    campaignId: '1',
    status: 'review',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-01',
    dueDate: '2025-02-15',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 80,
    createdAt: '2025-01-28',
  },
  {
    id: '3',
    title: 'Customer Testimonial Graphics',
    contentType: 'graphic',
    projectId: '1',
    status: 'in-progress',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-10',
    dueDate: '2025-02-20',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 60,
    createdAt: '2025-02-08',
  },
  {
    id: '4',
    title: 'Website Redesign Blog Article',
    contentType: 'article',
    projectId: '2',
    status: 'idea',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-01',
    dueDate: '2025-03-15',
    priority: 'low',
    attachments: [],
    comments: [],
    progress: 0,
    createdAt: '2025-02-25',
  },
  {
    id: '5',
    title: 'Eco Tips Instagram Post Series',
    contentType: 'post',
    projectId: '3',
    campaignId: '3',
    status: 'scheduled',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-02-20',
    dueDate: '2025-03-01',
    publishDate: '2025-03-05',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-02-18',
  },
  {
    id: '6',
    title: 'Product Showcase Video',
    contentType: 'video',
    projectId: '3',
    status: 'in-progress',
    assignedTo: '3',
    createdBy: '2',
    startDate: '2025-02-25',
    dueDate: '2025-03-10',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 45,
    createdAt: '2025-02-22',
  },
  {
    id: '7',
    title: 'Sustainability Email Newsletter',
    contentType: 'email',
    projectId: '3',
    status: 'approved',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-01',
    dueDate: '2025-03-08',
    publishDate: '2025-03-10',
    priority: 'medium',
    attachments: [],
    comments: [],
    progress: 100,
    createdAt: '2025-02-28',
  },
  {
    id: '8',
    title: 'Grand Opening Event Graphics',
    contentType: 'graphic',
    projectId: '4',
    campaignId: '4',
    status: 'idea',
    assignedTo: '4',
    createdBy: '2',
    startDate: '2025-03-20',
    dueDate: '2025-04-01',
    priority: 'high',
    attachments: [],
    comments: [],
    progress: 0,
    createdAt: '2025-03-15',
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    type: 'deadline',
    title: 'Task Due Soon',
    message: 'Setup Google Ads Campaign is due in 2 days',
    link: '/tasks/3',
    read: false,
    createdAt: '2025-10-01T08:00:00Z',
  },
  {
    id: '2',
    type: 'comment',
    title: 'New Comment',
    message: 'Emily Davis commented on "Write Blog Post - Product Features"',
    link: '/tasks/2',
    read: false,
    createdAt: '2025-09-30T14:30:00Z',
  },
  {
    id: '3',
    type: 'status-update',
    title: 'Task Completed',
    message: 'Website SEO Audit has been marked as complete',
    link: '/tasks/4',
    read: true,
    createdAt: '2025-09-29T10:15:00Z',
  },
  {
    id: '4',
    type: 'assignment',
    title: 'New Task Assigned',
    message: 'You have been assigned to "Design Grand Opening Flyers"',
    link: '/tasks/8',
    read: true,
    createdAt: '2025-09-28T09:00:00Z',
  },
];

